name: letstest
description: Progetto di Tesi di Andrea De Luna, A.A. 2020/2021.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  focus_detector: ^1.0.2
  fluttertoast: ^4.0.0
  wakelock: ^0.1.4+2
  pdf: ^1.5.0
  path_provider: ^1.6.5
  webview_flutter: ^2.0.9
  flutter_plugin_pdf_viewer: ^1.0.7
  share: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/